import Store from 'electron-store'
import { CONFIG_PATH } from './constant'

export const appConfigStore = new Store({
  name: 'app',
  cwd: CONFIG_PATH,
  fileExtension: 'conf',
  defaults: {
    close: {
      type: 0, // 0-退出程序  1-最小化
      remember: false,
    },
    autoTheme: true, // 自适应主题
    autoUseRune: false, // 自动应用符文
    onlyRankData: false, // 仅排位数据
    sendCoPlayer: true, // 发送组排信息
    sendPlayerLevelInfo: {
      enable: true, // 启用发送马匹信息
      title: ['老大', '老二', '老三', '老四', '老六'],
      template: '{称号}:{玩家名},kda:{kda},胜率:{胜率},近期:{对局}', // 战绩发送模板
      matchNum: 3, // 发送到KDA数量
    },
    blacklistNotice: false, // 黑名单提醒对所有人
    champToolWin: {
      enable: true, // 显示英雄工具小窗口
      flowGameWin: true, // 跟随游戏窗口
    },
    autoMatchingGame: {
      enable: false, // 自动匹配对局
      position: ['MIDDLE', 'FILL'],
    },
    autoAccept: {
      enable: true, // 自动接受对局
      delay: 3, // 延迟 秒
    },
    autoMute: false, // 开局禁言
    autoBanPick: {
      confirmSelect: true, // 自动确定英雄
      pick: {
        enable: false,
        normal: [],
        top: [],
        jungle: [],
        middle: [],
        bottom: [],
        utility: [],
      },
      ban: {
        enable: false,
        normal: [],
        top: [],
        jungle: [],
        middle: [],
        bottom: [],
        utility: [],
      },
    },
    /* 快捷键相关 */
    keys: {
      order: [61001],
      chaos: [61009],
      mute: [60999],
    },
  },
})
export const blacklistStore = new Store({
  name: 'blacklist',
  cwd: CONFIG_PATH,
  fileExtension: 'conf',
  defaults: {
    list: [],
  },
})
export const gameDataStore = new Store({
  name: 'game_data',
  cwd: CONFIG_PATH,
  fileExtension: 'conf',
  defaults: {
    version: '', //客户端版本
    champions: {}, // 以id英雄数据
    championDict: [], // 另一种结构形式的英雄数据
    championOptions: [], // 英雄选项
    items: [],
    runes: [],
    spells: {
      SummonerBarrier: {
        id: 'SummonerBarrier',
        name: '屏障',
        description: '为你的英雄套上护盾，吸收105-411（取决于英雄等级）伤害，持续2秒。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerBarrier.png',
        tooltip: '暂时为你的英雄套上持续2秒的护盾，抵挡{{ tooltipabsorbeddamage }}伤害。',
        cooldownBurn: '180',
        key: '21',
      },
      SummonerBoost: {
        id: 'SummonerBoost',
        name: '净化',
        description: '移除身上的所有限制效果（压制效果和击飞效果除外）和召唤师技能的减益效果，并且若在接下来的3秒里再次被施加限制效果时，新效果的持续时间会减少65%。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerBoost.png',
        tooltip: '移除你的英雄身上的所有限制效果（压制效果和击飞效果除外）和召唤师技能的减益效果，并且若在接下来的{{ e2 }}秒里再次被施加以上效果时，新效果的持续时间将减少65%。',
        cooldownBurn: '210',
        key: '1',
      },
      SummonerDot: {
        id: 'SummonerDot',
        name: '引燃',
        description: '引燃是对单体敌方目标施放的持续性伤害技能，在5秒的持续时间里造成70-410（取决于英雄等级）真实伤害，获得目标的视野，并减少目标所受的治疗和回复效果。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerDot.png',
        tooltip:
          '引燃目标敌人，在5秒的持续时间里造成共<span class="colorFEFCFF">{{ tooltiptruedamagecalculation }}</span>真实伤害，获得目标视野，并在持续期间为目标施加{{ grievousamount*100 }}%重伤效果。<br /><br /><rules>(重伤效果会使目标所受的治疗和回复效果降低，如果有多个重伤效果则取最高值。这个视野不会使潜行的敌人显形。)</rules>',
        cooldownBurn: '180',
        key: '14',
      },
      SummonerExhaust: {
        id: 'SummonerExhaust',
        name: '虚弱',
        description: '虚弱目标敌方英雄，降低其30%的移动速度，并使其造成的伤害减少40%，持续3秒。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerExhaust.png',
        tooltip: '虚弱目标英雄，降低目标{{ e5 }}%的移动速度，并使目标造成的伤害减少{{ damagereductiontooltip }}%，持续3秒。',
        cooldownBurn: '210',
        key: '3',
      },
      SummonerFlash: {
        id: 'SummonerFlash',
        name: '闪现',
        description: '使英雄朝着你的指针所停的区域瞬间传送一小段距离。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerFlash.png',
        tooltip: '使英雄朝着你的指针所停的区域瞬间传送一小段距离。',
        cooldownBurn: '300',
        key: '4',
      },
      SummonerHaste: {
        id: 'SummonerHaste',
        name: '幽灵疾步',
        description: '在10秒里，你的英雄可以无视单位的碰撞体积并且获得24~48%移动速度加成(基于英雄等级)。【幽灵疾步】会在参与击杀后延长其持续时间。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerHaste.png',
        tooltip: '在{{ duration }}秒里，你的英雄可以无视单位的碰撞体积并且获得{{ movespeedmod }}移动速度加成。<br /><br />【幽灵疾步】会在参与击杀后延长{{ takedownextension }}秒持续时间。',
        cooldownBurn: '210',
        key: '6',
      },
      SummonerHeal: {
        id: 'SummonerHeal',
        name: '治疗术',
        description: '为你和目标友军英雄回复80-318（取决于英雄等级）生命值，并为你和目标友军英雄提供30%移动速度加成，持续1秒。若目标近期已受到过其它治疗术的影响，则治疗术对目标产生的治疗效果减半。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerHeal.png',
        tooltip:
          '为你的英雄和目标友军英雄回复{{ tooltiphealamount }}（取决于英雄等级）生命值，并提供30%移动速度加成，持续1秒。若目标近期已受到过其它治疗术的影响，则治疗术对目标产生的治疗效果减半。<br /><br /><span class="colorFFFF00">如果这个技能无法找到目标，就会作用于范围内伤势最重的一位友军英雄。</span>',
        cooldownBurn: '240',
        key: '7',
      },
      SummonerMana: {
        id: 'SummonerMana',
        name: '清晰术',
        description: '为你的英雄回复50%的最大法力值。也会为周围的友军回复25%的最大法力值',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerMana.png',
        tooltip: '为你的英雄回复{{ e1 }}%的最大法力值，并为周围友军回复{{ e2 }}%最大法力值。',
        cooldownBurn: '240',
        key: '13',
      },
      SummonerPoroRecall: {
        id: 'SummonerPoroRecall',
        name: '护驾！',
        description: '快速位移到魄罗之王旁边。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerPoroRecall.png',
        tooltip:
          '<span class="colorFFE076">被动：</span>用魄罗命中一个敌方英雄，会为你的队伍提供一层魄罗印记。当魄罗印记达到10层时，你的队伍就可以召唤出魄罗之王来与你们并肩作战。在魄罗之王处于活跃状态时，双方队伍都无法获得魄罗印记。<br /><br /><span class="colorFFE076">主动：</span>快速冲刺到魄罗之王的身旁。只能在己方召唤了魄罗之王时施放。 <br /><br /><i><span class="colorFDD017">“魄罗们才是扣人心弦的焦点。而你们只是抱大腿的。”</span></i></mainText>',
        cooldownBurn: '10',
        key: '30',
      },
      SummonerPoroThrow: {
        id: 'SummonerPoroThrow',
        name: '魄罗投掷',
        description: '把一个魄罗投向你的敌人。如果它命中了一名敌人，那么你接下来就可以快速位移到被命中的敌人旁边。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerPoroThrow.png',
        tooltip:
          '将一个魄罗投向远处，对命中的第一个敌方单位造成{{ f2 }}真实伤害，并提供目标的<span class="coloree91d7">真实视野</span>。<br /><br />如果这个技能命中了一个敌人，那么在接下来的3秒里可以再次施放此技能，来冲到被命中的目标旁边，多造成{{ f2 }}真实伤害，并缩短下一个【魄罗投掷】{{ e4 }}秒冷却时间。<br /><br />魄罗们不会被法术护盾或各种墙体所格挡，因为它们是萌萌哒小动物，而不是技能！<br /><br /><i><span class="colorFDD017">“魄罗们是符文大陆空气动力学的一个科研模型。”</span></i></mainText>',
        cooldownBurn: '20',
        key: '31',
      },
      SummonerSmite: {
        id: 'SummonerSmite',
        name: '惩戒',
        description: '对目标史诗级野怪、大型野怪、中型野怪或小兵造成450真实伤害。在对抗野怪时，还会回复90 (+10%最大生命值)生命值。可持有2层充能(90秒充能时间)。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerSmite.png',
        tooltip:
          '对目标野怪或小兵造成<span class="colorFEFCFF">{{ smitebasedamage }}</span>真实伤害。对野怪时，额外回复<span class="colorFFFFFF">{{ smitebaseheal }}</span><span class="colorFF6666">(+{{ tooltipsmitehealaddition }})</span>生命值。<br /><br />【惩戒】每{{ ammorechargetime }}秒获得一层充能，最多可保持2层充能。<br /><br /><rules>无法对小型野怪施放。</rules>',
        cooldownBurn: '15',
        key: '11',
      },
      SummonerSnowURFSnowball_Mark: {
        id: 'SummonerSnowURFSnowball_Mark',
        name: '标记',
        description: '沿直线扔出一个雪球。如果雪球命中了一个敌人，那么这个敌人会被【标记】，提供真实视野，并且你的英雄接下来可以快速突进到被【标记】的目标旁边。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerSnowURFSnowball_Mark.png',
        tooltip:
          '扔出一个长程雪球，对命中的第一个敌方单位造成{{ tooltipdamagetotal }}真实伤害并提供目标的<span class="coloree91d7">真实视野</span>。如果雪球命中了一个敌人，那么这个技能可以在{{ e3 }}秒里再次施放，用来让英雄【冲刺】到目标单位旁边，同时造成额外的{{ tooltipdamagetotal }}真实伤害。在【冲刺】到目标旁边的同时，【标记】的冷却时间会减少{{ e4 }}%。<br /><br /><span class="colorFFFF00">【标记】的飞行道具不会被法术护盾或者飞行道具拦截技（亚索的【W风之障壁】、布隆的【E坚不可摧】）所阻挡。</span>',
        cooldownBurn: '80',
        key: '39',
      },
      SummonerSnowball: {
        id: 'SummonerSnowball',
        name: '标记',
        description: '沿直线扔出一个雪球。如果雪球命中了一个敌人，那么这个敌人会被【标记】，提供真实视野，并且你的英雄接下来可以快速突进到被【标记】的目标旁边。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerSnowball.png',
        tooltip:
          '扔出一个长程雪球，对命中的第一个敌方单位造成{{ tooltipdamagetotal }}真实伤害并提供目标的<span class="coloree91d7">真实视野</span>。如果雪球命中了一个敌人，那么这个技能可以在{{ e3 }}秒里再次施放，用来让英雄【冲刺】到目标单位旁边，同时造成额外的{{ tooltipdamagetotal }}真实伤害。在【冲刺】到目标旁边的同时，【标记】的冷却时间会减少{{ e4 }}%。<br /><br /><span class="colorFFFF00">【标记】的飞行道具不会被法术护盾或者飞行道具拦截技（亚索的【W风之障壁】、布隆的【E坚不可摧】）所阻挡。</span>',
        cooldownBurn: '80',
        key: '32',
      },
      SummonerTeleport: {
        id: 'SummonerTeleport',
        name: '传送',
        description: '在引导4秒后，将你的英雄传送到友方建筑物旁边。会在14分钟时升级为【解封的传送】，【解封的传送】可将你的英雄传送至友方建筑物、友方小兵或友方守卫旁边。',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/SummonerTeleport.png',
        tooltip:
          '在引导{{ channelduration }}秒后，将你的英雄传送到友方建筑物旁边。<br /><br />会在14分钟防御塔镀层脱落时升级为【解封的传送】。【解封的传送】拥有{{ upgradedcooldown }}秒冷却时间，可以用在友方的建筑物、小兵或守卫上，并提供{{ msamount*100 }}%移动速度加成，持续{{ msduration }}秒。',
        cooldownBurn: '360',
        key: '12',
      },
      Summoner_UltBookPlaceholder: {
        id: 'Summoner_UltBookPlaceholder',
        name: '占位',
        description: '这个栏位将在游戏开始后，被替换为所选的另一位英雄的终极技能。届时将有30秒的时间选择一个终极技能。请做好准备！',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/Summoner_UltBookPlaceholder.png',
        tooltip: '将被替换为你所选的终极技能。{{ spellmodifierdescriptionappend }}',
        cooldownBurn: '0',
        key: '54',
      },
      Summoner_UltBookSmitePlaceholder: {
        id: 'Summoner_UltBookSmitePlaceholder',
        name: '占位和攻击惩戒',
        description: '这个栏位将在游戏开始后，被替换为所选的另一位英雄的终极技能并且你将获得【攻击惩戒】。届时将有30秒的时间选择一个终极技能。请做好准备！',
        img: 'https://game.gtimg.cn/images/lol/act/img/spell/Summoner_UltBookSmitePlaceholder.png',
        tooltip:
          '将被替换为你所选的终极技能。<br /><br />提供【攻击惩戒】。【攻击惩戒】将在你攻击增益野怪、史诗级野怪和峡谷迅捷蟹时将其处决。<br /><br /><attention>【攻击惩戒】没有冷却时间。</attention>{{ spellmodifierdescriptionappend }}',
        cooldownBurn: '0',
        key: '55',
      },
    },
    constant: {
      position: {
        bottom: '下路',
        adc: '下路',
        jungle: '打野',
        middle: '中单',
        mid: '中单',
        support: '辅助',
        top: '上单',
      },
      status: {
        inQueue: '队列中',
        inGame: '游戏中',
        GameStart: '正在启动游戏',
        championSelect: '正在选择英雄',
        outOfGame: '正在退出游戏',
        hosting_NORMAL: '匹配组队中-队长',
        hosting_RANKED_SOLO_5x5: '单排组队中-队长',
        hosting_RANKED_FLEX_SR: '组排组队中-队长',
        hosting_ARAM_UNRANKED_5x5: '大乱斗5v5组队中-队长',
        hosting_URF: '无限火力组队中-队长',
        hosting_BOT: '人机组队中-队长',
        ChampSelect: '正在选择英雄',
        ReadyCheck: '等待接受对局',
        InProgress: '游戏中',
        Matchmaking: '正在寻找对局',
        Lobby: '在房间中',
        None: '在大厅发呆',
        EndOfGame: '退出游戏',
        WaitingForStats: '战绩面板',
        PreEndOfGame: '对局结束',
        Reconnect: '客户端重连中',
      },
      game: {
        CLASSIC: '经典模式',
        ARAM: '大乱斗',
        TFT: '云顶之弈',
        URF: '无限火力',
        PRACTICETOOL: '自定义',
      },
      match: {
        NORMAL: '匹配',
        RANKED_SOLO_5x5: '单双排',
        RANKED_FLEX_SR: '组排',
        ARAM_UNRANKED_5x5: '大乱斗5v5',
        URF: '无限火力',
        BOT: '人机',
        PRACTICETOOL: '自定义',
      },
      rank: {
        NONE: '无',
        IRON: '黑铁',
        BRONZE: '青铜',
        SILVER: '白银',
        GOLD: '黄金',
        PLATINUM: '白金',
        DIAMOND: '钻石',
        MASTER: '大师',
        GRANDMASTER: '宗师',
        CHALLENGER: '王者',
      },
      environment: {
        HN1: '艾欧尼亚',
        HN2: '祖安',
        HN3: '诺克萨斯',
        HN4: '班德尔城',
        HN5: '皮尔特沃夫',
        HN6: '战争学院',
        HN7: '巨神峰 ',
        HN8: '雷瑟守备',
        HN9: '裁决之地',
        HN10: '黑色玫瑰',
        HN11: '暗影岛',
        HN12: '钢铁烈阳 ',
        HN13: '水晶之痕',
        HN14: '均衡教派',
        HN15: '影流',
        HN16: '守望之海',
        HN17: '征服之海',
        HN18: '卡拉曼达',
        HN19: '皮城警备',
        WT1: '比尔吉沃特',
        WT2: '德玛西亚',
        WT3: '弗雷尔卓德',
        WT4: '无畏先锋',
        WT5: '恕瑞玛',
        WT6: '扭曲丛林',
        WT7: '巨龙之巢',
        HN1_NEW: '艾欧尼亚',
        HN2_NEW: '祖安',
        HN3_NEW: '诺克萨斯',
        HN4_NEW: '班德尔城',
        HN5_NEW: '皮尔特沃夫',
        HN6_NEW: '战争学院',
        HN7_NEW: '巨神峰 ',
        HN8_NEW: '雷瑟守备',
        HN9_NEW: '裁决之地',
        HN10_NEW: '黑色玫瑰',
        HN11_NEW: '暗影岛',
        HN12_NEW: '钢铁烈阳 ',
        HN13_NEW: '水晶之痕',
        HN14_NEW: '均衡教派',
        HN15_NEW: '影流',
        HN16_NEW: '守望之海',
        HN17_NEW: '征服之海',
        HN18_NEW: '卡拉曼达',
        HN19_NEW: '皮城警备',
        WT1_NEW: '比尔吉沃特',
        WT2_NEW: '德玛西亚',
        WT3_NEW: '弗雷尔卓德',
        WT4_NEW: '无畏先锋',
        WT5_NEW: '恕瑞玛',
        WT6_NEW: '扭曲丛林',
        WT7_NEW: '巨龙之巢',
        BGP1: '男爵领域,',
        TW2: 'RIOT-台服',
      }, // 地图id转描述
      queue: {
        '-1': '自定义',
        0: '训练模式',
        2: '匹配模式',
        4: '单双排位',
        6: '5v5 Ranked Premade games',
        7: 'Co-op vs AI games',
        8: '3v3 Normal games',
        9: '3v3 Ranked Flex games',
        14: '5v5 Draft Pick games',
        16: '5v5 Dominion Blind Pick games',
        17: '5v5 Dominion Draft Pick games',
        25: 'Dominion Co-op vs AI games',
        31: '人机对战',
        32: '人机对战',
        33: '人机对战',
        41: '3v3 Ranked Team games',
        42: '5v5 Ranked Team games',
        52: 'Co-op vs AI games',
        61: '5v5 Team Builder games',
        65: '极地乱斗',
        67: 'ARAM Co-op vs AI games',
        70: '克隆作战',
        72: '1v1 Snowdown Showdown games',
        73: '2v2 Snowdown Showdown games',
        75: '6v6 Hexakill games',
        76: 'Ultra Rapid Fire games',
        78: 'One For All: Mirror Mode games',
        83: 'Co-op vs AI Ultra Rapid Fire games',
        91: 'Doom Bots Rank 1 games',
        92: 'Doom Bots Rank 2 games',
        93: 'Doom Bots Rank 5 games',
        96: 'Ascension games',
        98: '6v6 Hexakill games',
        100: '极地乱斗',
        300: 'Legend of the Poro King games',
        310: 'Nemesis games',
        313: 'Black Market Brawlers games',
        315: 'Nexus Siege games',
        317: 'Definitely Not Dominion games',
        318: '火力',
        325: 'All Random games',
        400: '5v5 Draft Pick games',
        410: '5v5 Ranked Dynamic games',
        420: '单双排位',
        430: '匹配模式',
        440: '灵活组排',
        450: '极地乱斗',
        460: '3v3 Blind Pick games',
        470: '3v3 Ranked Flex games',
        600: 'Blood Hunt Assassin games',
        610: 'Dark Star: Singularity games',
        700: 'Clash games',
        800: '人机', //'Co-op vs. AI Intermediate Bot games',
        810: '人机', //'Co-op vs. AI Intro Bot games',
        820: '人机', //'Co-op vs. AI Beginner Bot games',
        830: '人机', //'Co-op vs. AI Intro Bot games',
        840: '人机', //'Co-op vs. AI Beginner Bot games',
        850: '人机', //'Co-op vs. AI Intermediate Bot games',
        900: '无限火力',
        910: 'Ascension games',
        920: 'Legend of the Poro King games',
        940: 'Nexus Siege games',
        950: 'Doom Bots Voting games',
        960: 'Doom Bots Standard games',
        980: 'Star Guardian Invasion: Normal games',
        990: 'Star Guardian Invasion: Onslaught games',
        1000: 'PROJECT: Hunters games',
        1010: '无限火力',
        1020: '克隆模式',
        1030: 'Odyssey Extraction: Intro games',
        1040: 'Odyssey Extraction: Cadet games',
        1050: 'Odyssey Extraction: Crewmember games',
        1060: 'Odyssey Extraction: Captain games',
        1070: 'Odyssey Extraction: Onslaught games',
        1090: 'Teamfight Tactics games',
        1100: 'Ranked Teamfight Tactics games',
        1110: 'Teamfight Tactics Tutorial games',
        1111: 'Teamfight Tactics test games',
        1200: 'Nexus Blitz games',
        1300: 'Nexus Blitz games',
        1400: '终极魔典',
        1900: '无限火力', // Pick URF games
        2000: 'Tutorial 1',
        2010: 'Tutorial 2',
        2020: 'Tutorial 3',
      },
      OPGGPosition: {
        TOP: '上单',
        JUNGLE: '打野',
        MID: '中单',
        ADC: 'ad',
        SUPPORT: '辅助',
      },
      role: {
        FIGHTER: '战士',
        SLAYER: '刺客',
        TANK: '坦克',
        MARKSMAN: '射手',
        CONTROLLER: '控制',
        MAGE: '法师',
      },
    },
  },
})
export const paidDataStore = new Store({
  name: 'paid_data',
  cwd: CONFIG_PATH,
  fileExtension: 'conf',
  encryptionKey: 'xiaowuyaya_tikleaguetool_1224',
  defaults: {
    enable: true,
    server: '101',
    server101: {
      Func: {
        自动换肤: true,
        云顶换肤: true,
        血液补丁: false,
        无限视距: false,
        补刀提示: false,
        血蓝显示: false,
        经验显示: false,
        人物大小: false,
        皮肤提示: true,
        皮肤修复: false,
        // 敌方
        敌方计时: false,
        敌方推送: false,
        敌方轨迹: false,
        陷阱透视: false,
        陷阱计时: false,
        眼位透视: false,
        眼位计时: false,
        眼位范围: false,
        走位轨迹: false,
        回城提示: false,
        回城透视: false,
        敌方野怪: false,
        敌方野计: false,
        敌方普攻: false,
        敌方炮塔: false,
        // 友方
        友方计时: false,
        友方推送: false,
        友方轨迹: false,
        友方野怪: false,
        友方野计: false,
        友方普攻: false,
        友方炮塔: false,
        // 自己
        Q技能范围: false,
        W技能范围: false,
        E技能范围: false,
        R技能范围: false,
        自己普攻: false,
      },
      Skin: {
        Minion: '0',
        Baron: '5',
        Red: '0',
        Razorbeak: '0',
        Ward: '0',
        Crab: '0',
        Blue: '0',
        Telepor: '0',
        Krug: '0',
      },
    },
  },
})
